onlyBuiltDependencies:
  - esbuild
  - phosart-bsky
  - phosart-common
  - sharp
  - msgpackr-extract
  - '@ffmpeg-installer/darwin-arm64'
  - '@ffmpeg-installer/darwin-x64'
  - '@ffmpeg-installer/linux-x64'
  - '@ffmpeg-installer/linux-ia32'
  - '@ffmpeg-installer/linux-arm'
  - '@ffmpeg-installer/win32-x64'
  - '@ffmpeg-installer/win32-ia32'
