onlyBuiltDependencies:
  - '@ffmpeg-installer/darwin-arm64'
  - '@ffmpeg-installer/darwin-x64'
  - '@ffmpeg-installer/linux-arm'
  - '@ffmpeg-installer/linux-ia32'
  - '@ffmpeg-installer/linux-x64'
  - '@ffmpeg-installer/win32-ia32'
  - '@ffmpeg-installer/win32-x64'
  - esbuild
  - msgpackr-extract
  - nodegit
  - phosart-bsky
  - phosart-common
  - sharp

overrides:
  phosart-common: link:../../../../Library/pnpm/global/5/node_modules/phosart-common
