steps:
  - name: ":node: build"
    command:
    - corepack enable
    - corepack install
    - pnpm ci
    - pnpm run build

  - name: ":node: build"
    command:
    - corepack enable
    - corepack install
    - pnpm ci
    - pnpm run test
